[package]
name = "picotool-cli"
version = "0.1.0"
edition = "2021"
license = "0BSD"

[dependencies]
camino = "1.1.9"
clap = { version = "4.5.17", features = ["derive"] }
env_logger = "0.11.5"
picotool = {path="../picotool", version = "0.1.0"}
